version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - microservices-net

  backend:
    build: ./backend
    ports:
      - "5000:3847"
    environment:
      - PORT=3847
      - MONGO_URI=mongodb://mongo:27017/ecom
    depends_on:
      - mongo
    networks:
      - microservices-net

  analytics:
    build: ./analytics-service
    ports:
      - "4001:4001"
    networks:
      - microservices-net

  notification:
    build: ./notification-service
    ports:
      - "4005:4002"
    networks:
      - microservices-net

  gateway:
    build: ./gateway
    ports:
      - "8000:80"
      - "443:443"
    networks:
      - microservices-net
    depends_on:
      - backend
      - analytics
      - notification

  prometheus:
    build: ./monitoring-stack/prometheus
    ports:
      - "9090:9090"
    networks:
      - microservices-net

  grafana:
    build: ./monitoring-stack/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  mongo-data:
