global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics:4001']

  - job_name: 'backend-service'
    static_configs:
      - targets: ['backend:3847']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification:4002']